- name: Get Status Ipv6
  hosts: all
  tasks:
   - name: Using Command 'ip addr show | grep inet6'
     shell: ip addr show | grep inet6
     register: statusIPV6

   - name: Debugging
     debug:
       var: statusIPV6

- name: Creating Report
  hosts: localhost
  tasks:
   - name: Using Template with Jinja 2
     template:
       src: ./report.template.j2
       dest: ./report.csv
